### ISSUE TITLE
Chrome autocomplete on text input 

### ISSUE THREAD

**Issue by anthonyseu** [jacgrady1/Casanova#20]
<img width="1435" alt="screen shot 2017-02-20 at 11 52 51 pm" src="https://cloud.githubusercontent.com/assets/3690006/23155515/bc3d6b16-f7c7-11e6-9946-dad263e444e6.png">

- [x] chrome autocomplete bug

**Comment by jacgrady1** [comment]
that is annoying! any way to fix that?

**Comment by anthonyseu** [comment]
> that is annoying! any way to fix that?

Probably shouldn't use material ui default text/password input
